from libraries import *
from parameters import *
from util import *

import os
from pathlib import Path
import numpy as np
import pandas as pd
import scipy.sparse as sp
import scanpy as sc

from sklearn.metrics.pairwise import cosine_distances
from joblib import Parallel, delayed
from statsmodels.stats.multitest import multipletests


def group_mean_from_X(X, idx):
    """Mean feature vector for rows X[idx, :]. Works for dense or sparse."""
    if sp.issparse(X):
        return np.asarray(X[idx, :].mean(axis=0)).ravel()
    return X[idx, :].mean(axis=0)


def distances_means_allcells_with_controlnull(
    adata,
    pert_col="target_gene",
    control_label="non-targeting",
    n_jobs=8,
    n_null=100,
    null_sample_size=3000,
    random_state=42,
    min_cells=20,
    use_pca=True,
    n_pcs=100,
    ctrl_mean_sample_size=50000,
):
    """
    For each perturbation, compute cosine distance between mean(pert) and mean(controls_mean_sample).
    Null distribution is generated by sampling from the remaining control cells (disjoint from the
    control-mean sample).

    Returns a DataFrame with perturbation rows + null rows.
    """
    rng = np.random.default_rng(random_state)

    # Choose representation
    if use_pca:
        if "X_pca" not in adata.obsm or adata.obsm["X_pca"].shape[1] < n_pcs:
            sc.pp.scale(adata, max_value=10)
            sc.tl.pca(adata, n_comps=max(50, n_pcs))
        X = np.asarray(adata.obsm["X_pca"][:, :n_pcs])
    else:
        X = adata.X

    obs = adata.obs[pert_col].astype(str).to_numpy()

    # Controls
    ctrl_idx = np.where(obs == control_label)[0]
    if len(ctrl_idx) < max(min_cells, null_sample_size, 2):
        raise ValueError(
            f"Not enough control cells ({len(ctrl_idx)}) for min_cells={min_cells} "
            f"and null_sample_size={null_sample_size}."
        )

    # Split controls into two disjoint pools
    ctrl_idx = rng.permutation(ctrl_idx)

    ctrl_mean_pool = ctrl_idx[:ctrl_mean_sample_size]
    ctrl_null_pool = ctrl_idx[ctrl_mean_sample_size:]

    if len(ctrl_null_pool) < null_sample_size:
        raise ValueError(
            f"Not enough remaining control cells for null sampling after taking "
            f"{ctrl_mean_sample_size} for ctrl_mean. Remaining={len(ctrl_null_pool)} < "
            f"null_sample_size={null_sample_size}. Reduce ctrl_mean_sample_size or null_sample_size."
        )

    ctrl_mean = group_mean_from_X(X, ctrl_mean_pool).reshape(1, -1)

    # Perturbations
    exclude = {control_label, "non_targeting", "non-targeting"}
    perts = sorted(set(obs) - exclude)
    tasks = [(p, np.where(obs == p)[0]) for p in perts if np.sum(obs == p) >= min_cells]

    def _one_pert(p, idx):
        mA = group_mean_from_X(X, idx).reshape(1, -1)
        cd = float(cosine_distances(mA, ctrl_mean)[0, 0])
        return {
            "perturbation": p,
            "n_pert": int(len(idx)),
            "n_ctrl_mean": int(len(ctrl_mean_pool)),
            "n_ctrl_null_pool": int(len(ctrl_null_pool)),
            "cosine_distance_means": cd,
        }

    pert_results = Parallel(n_jobs=n_jobs, backend="loky")(
        delayed(_one_pert)(p, idx) for p, idx in tasks
    )
    df_pert = pd.DataFrame(pert_results)

    # Null: control-vs-control, sampling only from remaining controls
    def _one_null(seed):
        rlocal = np.random.default_rng(seed)
        A_idx = rlocal.choice(ctrl_null_pool, size=null_sample_size, replace=False)
        mA = group_mean_from_X(X, A_idx).reshape(1, -1)
        cd = float(cosine_distances(mA, ctrl_mean)[0, 0])
        return {
            "perturbation": "control_vs_control",
            "n_pert": int(null_sample_size),
            "n_ctrl_mean": int(len(ctrl_mean_pool)),
            "n_ctrl_null_pool": int(len(ctrl_null_pool)),
            "cosine_distance_means": cd,
        }

    seeds = rng.integers(0, 2**32 - 1, size=n_null)
    null_results = Parallel(n_jobs=n_jobs, backend="loky")(
        delayed(_one_null)(int(s)) for s in seeds
    )
    df_null = pd.DataFrame(null_results)

    df = pd.concat([df_pert, df_null], ignore_index=True)
    df = df.sort_values(["perturbation"]).reset_index(drop=True)
    return df


def add_significance_to_df(df):
    """
    Add empirical p-values, q-values, and z-scores for cosine_distance_means.
    Null rows are those with perturbation == 'control_vs_control'.
    """
    df = df.copy()

    null_mask = df["perturbation"] == "control_vs_control"
    null_df = df[null_mask]
    obs_df = df[~null_mask].copy()

    null_cosine = null_df["cosine_distance_means"].values
    n_null = len(null_cosine)
    if n_null < 5:
        raise ValueError("Too few null samples to estimate significance reliably.")

    null_mean = np.mean(null_cosine)
    null_std = np.std(null_cosine, ddof=1) if n_null > 1 else np.nan

    obs_df["z_cosine"] = (obs_df["cosine_distance_means"] - null_mean) / null_std

    def empirical_pval(x):
        ge = np.sum(null_cosine >= x)
        return (ge + 1.0) / (n_null + 1.0)

    obs_df["pval_cosine"] = [empirical_pval(x) for x in obs_df["cosine_distance_means"].values]
    _, obs_df["qval_cosine"], _, _ = multipletests(obs_df["pval_cosine"].values, method="fdr_bh")

    merged = pd.concat([obs_df, null_df], ignore_index=True)

    for col in ["z_cosine", "pval_cosine", "qval_cosine"]:
        if col not in merged.columns:
            merged[col] = np.nan

    return merged


def run_split_chunks_with_controls(
    cond: str,
    split_dir: str,
    controls_path: str,
    out_dir: str | None = None,
    *,
    pert_col="target_gene",
    control_label="non-targeting",
    use_pca=True,
    n_pcs=50,
    n_jobs=8,
    n_null=100,
    null_sample_size=2000,
    random_state=42,
    min_cells=50,
    join="inner",
):
    """
    For each ad_###.h5ad in `split_dir`:
      1) read chunk
      2) read controls
      3) concatenate chunk + controls
      4) compute distances + significance
      5) write per-chunk CSV

    New behavior:
      - checks which output files already exist
      - skips completed chunks
      - processes only the remaining chunks
    """
    split_dir = Path(split_dir)
    controls_path = str(controls_path)
    out_dir = Path(out_dir or (split_dir / "cosine_outputs"))
    out_dir.mkdir(parents=True, exist_ok=True)

    # Discover chunk files
    chunk_files = sorted(split_dir.glob("ad_*.h5ad"))
    if len(chunk_files) == 0:
        raise FileNotFoundError(f"No files matching ad_*.h5ad found in {split_dir}")

    # Keep only real chunk files, not the controls file if it happens to match
    chunk_files = [x for x in chunk_files if x.name != f"{cond}_controls.h5ad"]

    if len(chunk_files) == 0:
        raise FileNotFoundError(f"No chunk files left after excluding controls in {split_dir}")

    # Check already completed outputs
    pending_chunk_files = []
    done_chunk_files = []

    for chunk_path in chunk_files:
        chunk_name = chunk_path.stem  # e.g. ad_001
        out_csv = out_dir / f"{cond}_{chunk_name}_pca_cosineRes_{n_pcs}Pcs.csv"
        print(out_csv)
        
        if out_csv.exists():
            done_chunk_files.append(chunk_path)
        else:
            pending_chunk_files.append(chunk_path)

    print(f"\nCondition: {cond}")
    print(f"Total chunk files found: {len(chunk_files)}")
    print(f"Already completed:      {len(done_chunk_files)}")
    print(f"Remaining to process:   {len(pending_chunk_files)}")

    if len(done_chunk_files) > 0:
        print("\nSkipping already existing outputs:")
        for x in done_chunk_files:
            print(f"  - {x.stem}")

    if len(pending_chunk_files) == 0:
        print("\nNothing to do. All chunk outputs already exist.")
        return

    all_results = []

    for chunk_path in pending_chunk_files:
        chunk_name = chunk_path.stem
        out_csv = out_dir / f"{cond}_{chunk_name}_pca_cosineRes_{n_pcs}Pcs.csv"

        print(f"\n=== Processing {cond}: {chunk_name} ===")

        # Load chunk + controls
        ad_chunk = sc.read_h5ad(str(chunk_path))
        ad_ctrl = sc.read_h5ad(controls_path)

        ad_ctrl = ad_ctrl[
            ~ad_ctrl.obs["assignment_geomux"].isin([
                "non-targeting_00632|non-targeting_01620",
                "non-targeting_00167|non-targeting_00392",
                "non-targeting_00811|non-targeting_01928",
                "non-targeting_00081|non-targeting_03672",
                "non-targeting_00707|non-targeting_00071",
                "non-targeting_00210|non-targeting_02497",
                "non-targeting_00539|non-targeting_03531",
            ]),
            :
        ]

        if pert_col not in ad_chunk.obs.columns:
            raise KeyError(f"{chunk_name}: '{pert_col}' not found in chunk obs")
        if pert_col not in ad_ctrl.obs.columns:
            raise KeyError(f"controls: '{pert_col}' not found in controls obs")

        adata = sc.concat(
            {"chunk": ad_chunk, "controls": ad_ctrl},
            axis=0,
            join=join,
            merge="same",
            label="source",
        )

        df = distances_means_allcells_with_controlnull(
            adata,
            pert_col=pert_col,
            control_label=control_label,
            n_jobs=n_jobs,
            n_null=n_null,
            null_sample_size=null_sample_size,
            random_state=random_state,
            min_cells=min_cells,
            use_pca=use_pca,
            n_pcs=n_pcs,
        )

        res = add_significance_to_df(df)
        res["condition"] = cond
        res["chunk"] = chunk_name

        res.to_csv(out_csv, index=False)
        print(f"  wrote: {out_csv}")

        all_results.append(res)

        del ad_chunk, ad_ctrl, adata

    return


# =========================
# RUN
# =========================
cond = "AR-A014418"

#for cond in ["AR-A014418", "AZD4573", "CHIR-98014", "DMSO_round2", "Lexibulin", "PP121", "Romidepsin", "Stattic"]:
for cond in [ "LY2090314", "NSC95397",  "VX-11e"] :
    split_dir = f"/processed_datasets/VCI/ChemoGenetic_H1_Basak/{cond}/SPLIT/"
    controls_path = f"/processed_datasets/VCI/ChemoGenetic_H1_Basak/{cond}/SPLIT/{cond}_controls.h5ad"
    
    run_split_chunks_with_controls(
        cond=cond,
        split_dir=split_dir,
        controls_path=controls_path,
        out_dir=f"/home/beraslan/Projects/ChemoGeneticScreens/DATA/{cond}/",
        pert_col="target_gene",
        control_label="non-targeting",
        use_pca=True,
        n_pcs=100,
        n_jobs=8,
        n_null=300,
        null_sample_size=3000,
        random_state=42,
        min_cells=20,
        join="inner",
    )